language: cpp

os: windows

before_install:
    - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Product.Community --includeRecommended --includeOptional --passive --locale en-US"
    - ls -al /c/Program\ Files\ \(x86\)/
    - ls -al /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio

install:
    - mkdir doxygen && cd doxygen
    - curl -o doxygen.zip http://doxygen.nl/files/doxygen-1.8.16.windows.x64.bin.zip
    - unzip doxygen.zip
    - export PATH=$PATH:$PWD
    - cd ..

script: 
    - cd bin
    - cmake .. -G "Visual Studio 16 2019"
    - cmake --build . --target GEGELATI --config Debug
    - cmake --build . --target GEGELATI --config Release
    - cmake --build . --target doc
    - cmake --build . --target INSTALL --config Debug
    - cmake --build . --target INSTALL --config Release
    - cmake --build . --target runTests --config Debug
    - ./bin/Debug/runTests.exe