language: cpp

os: windows

script: 
    - cd bin
    - cmake ..
    - cmake --build . --target GEGELATI --config Debug
    - cmake --build . --target GEGELATI --config Release
    - cmake --build . --target doc
    - cmake --build . --target INSTALL --config Debug
    - cmake --build . --target INSTALL --config Release
    - cmake --build . --target runTests --config Debug