name: CI
on: [push]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    name: Ubuntu-${{ matrix.compiler }}
    env:
      GENERATOR: 'Unix Makefile'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          sudo apt install doxygen
      - name: Build
        run: |
          cd bin
          cmake .. -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --target GEGELATI
          cmake --build . --target doc
          sudo make install
          cmake --build . --target runTests
      - name: Run Tests
        run: |
          cd bin
          ./bin/runTests
  Windows-MSVC:
    runs-on: windows-latest
    env:
      GENERATOR: 'Visual Studio 16 2019'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 1
          retry_on: error
          command: choco install doxygen.install --force
          shell: bash
      - name: Build
        run: |
          cd bin
          cmake ..
          cmake --build . --target GEGELATI --config Debug
          cmake --build . --target doc
          cmake --build . --target INSTALL --config Debug
          if [ ${GITHUB_REF##*/} == "develop" ] || [ ${GITHUB_REF##*/} == "master" ] ; then cmake --build . --target INSTALL --config Release ; fi;
          cmake --build . --target runTests --config Debug
        shell: bash
      - name: Run Tests
        run: ./bin/bin/Debug/runTests.exe
        shell: bash