name: ubuntu-gcc
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GENERATOR: 'Unix Makefile'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          sudo apt install doxygen gcovr
      - name: Build
        run: |
          cd bin
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --target GEGELATI
          cmake --build . --target doc
          sudo make install
          cmake --build . --target runTests
      - name: Run Tests
        run: |
          cd bin
          ./bin/runTests